// Generated by Wrangler

import type { CookieOptions } from "@supabase/ssr";

// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
type Env = {
	SUPABASE_URL(
		SUPABASE_URL: string,
		SUPABASE_ANON_KEY: string,
		arg2: {
			cookies: {
				getAll(): { name: string; value: string }[];
				setAll(
					cookiesToSet: {
						name: string;
						value: string;
						options: CookieOptions;
					}[],
				): void;
			};
			cookieOptions: { httpOnly: true; secure: true };
		},
	): unknown;
	FRONTEND_URL: string;
};
